### ISSUE TITLE
getInterations return type

### ISSUE THREAD

**Issue by Dogantoro** [Dogantoro/rx-warning#3]
`getInteractions(std::string drug)` should return a complete DrugInfo instance. Currently, one of them returns a vector of interaction severities and one returns a vector of interaction descriptions.

**Comment by melodusk** [comment]
for adjList i can see how you could return drug info instead of interaction severities, but for adjMatrix im not sure how you could do that because a coordinate in the matrix would just represent the interactions between two drugs, so you cant just return 1 drug info unless you want getInteractions to return multiple drugs with adjMatrix.

**Comment by melodusk** [comment]
also the whole point of getInteractions is to just get the interactions. getting info about the drugs can be accomplished by using different functions that I can make, or by just getting the drugInfo directly in a separate function and then getting its attributes

**Comment by melodusk** [comment]
Ok we discussed this and I think I fixed this
